INSERT INTO CUSTOMER VALUES (1, 'Ali Khan', '03001234567', 'ali@gmail.com');
INSERT INTO CUSTOMER VALUES (2, 'Ahmed Raza', '03111234567', 'ahmed@gmail.com');

INSERT INTO RESTAURANT VALUES (1, 'Pizza Hub', 'Rawalpindi');
INSERT INTO RESTAURANT VALUES (2, 'Burger House', 'Islamabad');

INSERT INTO FOOD VALUES (1, 'Pizza', 1200, 1);
INSERT INTO FOOD VALUES (2, 'Burger', 500, 2);

INSERT INTO ORDERS VALUES (1, 1, SYSDATE, 1200);
INSERT INTO ORDERS VALUES (2, 2, SYSDATE, 500);

INSERT INTO ORDER_DETAILS VALUES (1, 1, 1, 1);
INSERT INTO ORDER_DETAILS VALUES (2, 2, 2, 1);

INSERT INTO PAYMENT VALUES (1, 1, 1200, 'Cash', 'Paid');
INSERT INTO PAYMENT VALUES (2, 2, 500, 'Card', 'Paid');